services:
  db:
    image: postgres:16
    container_name: ekubcircle-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ekubcircle
    ports:
      - "5432:5432"
    volumes:
      - ekubcircle_pg:/var/lib/postgresql/data

volumes:
  ekubcircle_pg:
